default_language_version:
    python: python3.11.3

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: check-ast
          - id: trailing-whitespace
          - id: check-yaml
          - id: check-json
          - id: check-xml
          - id: check-builtin-literals
          - id: check-merge-conflict
          - id: check-case-conflict
          - id: check-docstring-first
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: check-executables-have-shebangs
            args: [--fix=auto]


    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            args: [--config, ./pyproject.toml]


    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--profile", "black", --settings-path=pyproject.toml]
            name: isort (python)

    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.15.0
      hooks:
          - id: eslint


    - repo: local
      hooks:
          - id: run pytest
            name: pytest
            entry: poetry
            args: [run, pytest, -vv]
            pass_filenames: false
            language: system

    - repo: https://github.com/myint/docformatter
      rev: v1.4
      hooks:
          - id: docformatter
            args: [--in-place]

    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
            args: [
                    "-rn", # Only display messages
                    # "--rcfile=.pylintrc", # Link to your config file
                ]

    - repo: https://github.com/myint/autoflake
      rev: 'v1.4'
      hooks:
        - id: autoflake
          args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']


    - repo: local
      hooks:
        - id: jupyter-nb-clear-output
          name: jupyter-nb-clear-output
          files: \.ipynb$
          stages: [commit]
          language: system
          entry: python -m nbconvert --ClearOutputPreprocessor.enabled=True --inplace
