# Generated by Django 4.0.3 on 2022-03-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitcoin',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('dividends', models.IntegerField(blank=True, null=True)),
                ('stock_splits', models.IntegerField(blank=True, db_column='stock splits', null=True)),
            ],
            options={
                'verbose_name_plural': 'Bitcoin',
                'db_table': 'bitcoin',
            },
        ),
        migrations.CreateModel(
            name='Dollar',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('dividends', models.IntegerField(blank=True, null=True)),
                ('stock_splits', models.IntegerField(blank=True, db_column='stock splits', null=True)),
            ],
            options={
                'verbose_name_plural': 'Dollar',
                'db_table': 'dollar',
            },
        ),
        migrations.CreateModel(
            name='FiiBr',
            fields=[
                ('symbol', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('full_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'FII Brazil',
                'db_table': 'fii_br',
            },
        ),
        migrations.CreateModel(
            name='Ibovespa',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('dividends', models.IntegerField(blank=True, null=True)),
                ('stock_splits', models.IntegerField(blank=True, db_column='stock splits', null=True)),
            ],
            options={
                'verbose_name_plural': 'Ibovespa',
                'db_table': 'ibovespa',
            },
        ),
        migrations.CreateModel(
            name='Nasdaq',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('dividends', models.IntegerField(blank=True, null=True)),
                ('stock_splits', models.IntegerField(blank=True, db_column='stock splits', null=True)),
            ],
            options={
                'verbose_name_plural': 'Nasdaq',
                'db_table': 'nasdaq',
            },
        ),
        migrations.CreateModel(
            name='Smal',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('dividends', models.IntegerField(blank=True, null=True)),
                ('stock_splits', models.IntegerField(blank=True, db_column='stock splits', null=True)),
            ],
            options={
                'verbose_name_plural': 'Small',
                'db_table': 'smal',
            },
        ),
        migrations.CreateModel(
            name='SP_500',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('dividends', models.IntegerField(blank=True, null=True)),
                ('stock_splits', models.IntegerField(blank=True, db_column='stock splits', null=True)),
            ],
            options={
                'verbose_name': 'S&P 500',
                'verbose_name_plural': 'S&P 500',
                'db_table': 'sp_500',
            },
        ),
        migrations.CreateModel(
            name='Stocks_br',
            fields=[
                ('symbol', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('isin', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stocks Brazil',
                'db_table': 'stocks_br',
            },
        ),
        migrations.CreateModel(
            name='StocksIbov',
            fields=[
                ('symbol', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('quantity', models.TextField(blank=True, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stocks Ibovespa',
                'db_table': 'stocks_ibov',
            },
        ),
        migrations.CreateModel(
            name='Xfix',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('dividends', models.IntegerField(blank=True, null=True)),
                ('stock_splits', models.IntegerField(blank=True, db_column='stock splits', null=True)),
            ],
            options={
                'verbose_name_plural': 'Xfix',
                'db_table': 'xfix',
            },
        ),
    ]
