# Generated by Django 4.0.3 on 2022-04-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FiiBr',
            new_name='Fii',
        ),
        migrations.AlterModelTable(
            name='fii',
            table='fiis',
        ),
    ]
